### ISSUE TITLE
[FEAT] Documentation fix

### ISSUE THREAD

**Issue by salamander2** [linuxserver/docker-mysql-workbench#16]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Your documentation does not say whether your mysql-workbench image includes MySQL or not. There's literally not one sentence that clarifies this. You could say one of the following:

* "This image comes with mysql built in"
* "This image has MariaDB version x,y.z installed"
* "This image does NOT include MySQL, however we do kindly provide instructions for how to connect your MySQL container to this one".

Please add a `docker-compose.yml` that shows how to connect MySQL-workbench to MySQL server.  (Assuming that it is not already included.) 

Thanks.       
(Note: I have not yet downloaded it and tried it out to see exactly what the status is. I'll do that this evening. I'm just astonished about this omission in the documentation.)

### Reason for change

Clarity. Need I say more?

### Proposed code change

_fixed up docker-compose.yml_

**Comment by j0nnymoe** [comment]
Mysql-workbench is a separate product to mysql, much like it is advertised on mysql's website itself. 

It's a tool to run SQL queries against MySQL/MariaDB servers much like Microsoft's SQL Management Studio. 

There is no need to add adjust the compose to show how to deploy/connect to a MySQL server with this product because it's a desktop application (within a kasmvnc instance) which you would then add your connection details to for your various servers.

I would suggest attempting to deploy the container first before asking for clarity/changes so you can see what the application is / how it works.

**Comment by Roxedus** [comment]
mysql-workbench as a application does not bundle mysql, that fact should make it clear if it is included in the image

**Comment by aptalca** [comment]
The image has `mysql-workbench`. Nothing more, nothing less. The description in the image links to the website of the product, which explains what it is.

Don't get astonished if a potato peeler doesn't say whether it comes with potatoes or not. It's a potato peeler, that's all. You provide your own potatoes.

**Comment by salamander2** [comment]
FYI. 
:star: **For anyone who is looking for how to connect this MySQL-WorkBench container to MYSQL, here's the information you need.**

`docker-compose.yml`

```name: sqlbench
services:
  workbench:
    image: linuxserver/mysql-workbench:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - "./wbData:/config"
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - IPC_LOCK
    #restart: unless-stopped

  sqldb:
    image: mysql:8.0.36-debian
    environment:
      MYSQL_ROOT_PASSWORD: devstack
      TZ: America/Toronto
    ports:
      - 3306:3306
    #restart: unless-stopped
    volumes:
      - "./sqlData:/var/lib/mysql"
```

:pencil2: NOTE: the most recent MySQL version is not supported.


:boom: And the critical part:  Once you start MySQL-Workbench (ie. browsing to localhost:3000), you need to setup the database connection. HOWEVER "localhost:3306" does not wok.  **You have to use the container name "sqldb:3306"**
