### ISSUE TITLE
Cannot connect to MySQL Server (Keyring Issue) when running on Windows 10 Machine

### ISSUE THREAD

**Issue by kamaruzzaman** [linuxserver/docker-mysql-workbench#3]
Hi,

I have started the mysql workbench on a Windows machine with the following command:

docker run --name mk-workbench -p3000:3000 -v workbench-volume:/config -d linuxserver/mysql-workbench

It works successfully. I can also connect to localhost:3000. 

But then, I cannot connect to the running MySQL server and got the following exception:

"Error Calling StartServerByName ...."

For complete error message, please check the attachment:

![workbench_error](https://user-images.githubusercontent.com/8328718/83982655-b2192600-a928-11ea-96e8-e9b78d3807c5.png)

**Comment by thelamer** [comment]
you need the IPC cap in the documentation: 
```
--cap-add="IPC_LOCK"
```
I am not sure if that is compatible with windows though.
